project:
  type: website

website:
  title: "Francisco J. Rubilar Rocha"
  description: "Ingeniero Civil Ambiental | Magíster en Manejo de Recursos Naturales"
  site-url: fcorubilarrocha@gmail.com
  navbar:
    title: |
      Francisco J. Rubilar Rocha
    subtitle: "Ing. Civil Ambiental · Magíster RRNN"
    right:
      - text: "Sobre mí"
        href: about.qmd
      - text: "Artículos"
        href: index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css